-- Update admin password
-- Run this migration to update the admin password in the database

-- Generate new password hash for 'lumi2012grade'
-- Hash: $2a$10$xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx (will be generated by bcrypt)

-- Update admin password
UPDATE admin_users 
SET password = $2a$10$N9qo8uLOickgx2ZMRZoMyeIjZAgcfl7p92ldGxad68LJZdL17lhWy
WHERE username = 'admin';

-- Note: The hash above is bcrypt hash of 'lumi2012grade'
-- To generate a new hash for different password, use:
-- const bcrypt = require('bcryptjs');
-- const hash = bcrypt.hashSync('yourpassword', 10);
